name: recud
description: "A new Flutter project."
publish_to: "none"
version: 1.4.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: 6.2.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  overlay_support: 2.1.0
  loading_animation_widget: 1.3.0
  flutter_launcher_icons: 0.14.2
  flutter_native_splash: 2.4.3
  flutter_inappwebview: 6.1.5
  image_picker: 1.1.2
  permission_handler: 12.0.1
  get_thumbnail_video: 0.7.3
  path_provider: 2.1.5
  video_player: 2.10.0
  in_app_purchase: 3.2.1
  intl: 0.20.2
  record: 6.0.0
  just_audio: 0.10.4
  flutter_keychain: 2.5.0
  camera: 0.11.2
  device_info_plus: ^11.3.0
  vpn_detector: 1.2.0
  devicelocale: ^0.8.1
  flutter_native_timezone: ^2.0.0
  system_keyboard_languages: ^0.0.2
  encrypt: ^5.0.0
  http: 1.3.0
  flutter_local_notifications: 18.0.1
  screen_protector: 1.3.0
  facebook_app_events: 0.19.3
  convert: 3.1.2
  url_launcher: 6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: truedevicelocale
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/aisncuicon.png"

flutter_native_splash:
  background_image: "assets/images/zxopcijiqd.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
